@startuml

header
DRAFT
Authors: Olivier Wouters
Version: 0.1.0
endheader

title Types - Class Diagram

package ProductAggregate <<Cloud>> {

  class Product {
      gtin: String
      name: String
      description: String
      images: [Image]
      categories: [ProductCategory]
      contributions: [ProductContribution]
      ingredients: [ProductIngredient]
  }
  
  Product *-right-{ ProductContribution
  Product *-down-{ ProductCategory
  Product *-left-{ ProductIngredient
  
  class ProductContribution {
      actorKey: String
      isMain: Boolean
      roles: [ProducContributionRoleType]
  }
  
  ProductContribution -down[hidden]- ProducContributionRoleType
  
  enum ProducContributionRoleType {
    Producer
    Transformer
    Packer
  }
  
  class ProductCategory {
    categoryKey: String
  }
  
  class ProductIngredient {
      name: String
  }
}

ProductAggregate -right[hidden]- ActorAggregate

package ActorAggregate <<Cloud>> {

  ProductContribution::actorKey .. Actor

  class Actor {
    key: String
    name: String
    place: Address
    location: Location
    images: [Image]
  }
  
  Actor *-down- Address
  Actor *-right- Location
  
  class Address {
    street: String
    postCode: String
    locality: String
    country: AddressArea
  }
  
  Address::country *-right- AddressArea
  
  class AddressArea {
    code: String
    name: String
  }
  
  AddressArea::code *.right. Area
  
  class Area {
    type: AreaType
    code: String
    name: String
  }
  
  Area .up[hidden]. AreaType
  
  enum AreaType {
      Country
  }
  
  class Location {
      latitude: Float
      longitude: Float
  }

}


package ClassificationService {

  ProductCategory .down. Category
  
  class Classification {
    key: String
    name: String
  }
  
  Category::classificationKey *.left. Classification
  Category *.right. Category : parent-child
  
  class Category {
    key: String
    name: String
    classificationKey: Classification
    hierarchyLevel: Int
    parentKey: String
  }
}

@enduml
