@startuml

header
DRAFT
Authors: Olivier Wouters
Version: 0.3.0
endheader

legend right
    | Color | Type |
    |<#ff7f00>| A for Aggregate|
    |<#90ee90>| V for ValueObject|
endlegend

title Product context

namespace Main {
  
  class Address << (V,lightgreen) >> {
    street: String
    postCode: String
    locality: String
  }
  
  Address *-- AddressArea : country
  Address *-- AddressArea : administrativeLevel1
  Address *-- AddressArea : administrativeLevel2
  
  class AddressArea << (V,lightgreen) >> {
    code: String
    name: String
  }
  
  AddressArea::code *.. Area
  
  class Area << (A,orange) >> {
    type: AreaType
    code: String
    name: String
  }
  
  Area .up[hidden]. AreaType
  
  enum AreaType {
      Country
  }
  
  class Location << (V,lightgreen) >> {
      latitude: Float
      longitude: Float
  }
  
  
  namespace ActorService {
  
    class Actor << (A,orange) >> {
      id: Id
      key: String
      name: String
      images: [Image]
    }
    
    Actor *-- Main.Address : address
    Actor *-- Main.Location : location
    
    class Membership << (A,orange) >> {
      groupId: Id
      memberId: Id
    }
  
    Actor *..{ Membership : members
    Actor *..{ Membership : groups
  }
  
  namespace ClassificationService {
    
    class Classification << (A,orange) >> {
      type: String
      key: String
      name: String
    }
    
    class Category << (A,orange) >> {
      key: String
      name: String
      classificationKey: String
      hierarchyLevel: Int
      parentKey: String
    }
    
    Category::classificationKey *.left. Classification
    Category *.right. Category : parent-child
  }
  
  namespace ProductService {
  
    class Product << (A,orange) >> {
      id: Id
      familyId: Id
      gtin: String
      name: String
      description: String
      images: [Image]
    }
    
    Product *-right-{ ProductContribution : contributions
    Product *-down-{ ProductCategory :  categories
    Product::familyId *.left. ProductFamily : family
    Product *--{ ProductIngredient : ingredients
    
    class ProductContribution << (V,lightgreen) >> {
        actorId: Id
        isMain: Boolean
    }
    
   ProductContribution::actorId *..  Main.ActorService.Actor : actor
    
    ProductContribution *-down-{ ProductContributionRole : roles
    
    enum ProductContributionRoleType {
      Producer
      Transformer
      Packer
    }
    
    class ProductContributionRole << (V,lightgreen) >> {
      type: ProductContributionRoleType
    }
    
    class ProductCategory << (V,lightgreen) >> {
      categoryKey: String
    }
  
    ProductCategory::categoryKey *.down. Main.ClassificationService.Category
    
    class ProductIngredient << (V,lightgreen) >> {
        name: String
    }
    
    class ProductFamily << (A,orange) >> {
      name: String
      description: String
      images: [Image]
      categories: [ProductCategory]
      contributions: [ProductContribution]
      ingredients: [ProductIngredient]
    }
  }
}

@enduml
